default_context:
  project_name: 'MEWAYZ-V2'
  project_slug: 'mewayz-v2'
  domain_main: 'mewayz.app'
  domain_staging: 'stag.mewayz.app'
  domain_base_api_url: 'http://mewayz.app/api/v1'
  domain_base_ws_url: 'ws://mewayz.app/api/v1'
  docker_swarm_stack_name_main: 'mewayz-app'
  docker_swarm_stack_name_staging: 'stag-mewayz-app'
  secret_key: 'changethis'
  first_superuser: 'admin@mewayz.app'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.mewayz.app", "https://stag.mewayz.app", "https://mewayz.app"]'
  smtp_tls: 'True'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@mewayz.app'
  smtp_emails_from_name: 'Symona Adaro'
  smtp_emails_to_email: 'info@mewayz.app'
  mongodb_uri: 'mongodb'
  mongodb_database: 'mewayz'
  traefik_constraint_tag: 'mewayz.app'
  traefik_constraint_tag_staging: 'stag.mewayz.app'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
